In [1]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
np.array(benimListem)

array([20, 30, 40])

In [4]:
np.array([[10,20,30],[20,30,40],[30,40,50]])

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## linspace

In [9]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [2]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [11]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [12]:
np.random.randn(8)

array([ 0.81206301, -0.64619934,  0.24425945,  0.06861779, -0.77099853,
       -1.27299281, -1.3835481 ,  0.07524251])

In [13]:
np.random.randint(1,10,3)

array([4, 8, 9])

# Numpy Dizi Metodları

In [14]:
randomList = np.random.randint(0,50,30)

In [15]:
randomList.reshape(5,6)

array([[10, 12, 10, 14, 29,  8],
       [13,  9, 24, 35, 35, 16],
       [43, 45, 30, 31, 47, 37],
       [16, 19, 31,  6,  3, 37],
       [22,  5, 40, 17, 18, 25]])

In [16]:
randomList.argmax()

16

In [17]:
randomList.shape

(30,)

In [18]:
reshapedList = randomList.reshape(5,6)

In [19]:
reshapedList.shape

(5, 6)