In [1]:
import numpy as np

In [2]:
myArray = np.arange(0,15)

In [3]:
myArray[3:5]

array([3, 4])

In [4]:
myArray[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [5]:
myArray[::-2]

array([14, 12, 10,  8,  6,  4,  2,  0])

## matrix

In [7]:
matrixArray = np.array([[10,20,30],[20,30,40],[40,50,60]])

In [8]:
matrixArray

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [9]:
matrixArray[2:,0:]

array([[40, 50, 60]])

In [10]:
matrixArray[0:,2:]

array([[30],
       [40],
       [60]])

## operasyonlar

In [12]:
newArray = np.random.randint(1,100,20)

In [13]:
newArray>24

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True, False,  True,
       False,  True])

In [14]:
newArray[newArray>24]

array([33, 51, 26, 86, 80, 72, 37, 45, 29, 42, 51, 62, 63, 63])

In [15]:
lastArray = np.arange(0,24)